name: Basic Workflow
on:
  push:
    branches:
      - caracteristica/flujo-basico

jobs:
  do-things:
    name: Do Things
    runs-on: ubuntu-latest
    steps:
      - name: Logrado
        run: echo "Lo he logrado!"
      - name: Provocando un error
        run: |
          echo "Cometí un error!"
          exit 1